# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="bd44cc09-b021-4db8-9e7a-67f9aa5c9ce3"


# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -mironec@tut.by
    on_success: never # default: change
    on_failure: always # default: always